### ISSUE TITLE
Conditionally loading javascript in the hook.php file

### ISSUE THREAD

**Issue by tompha** [wp-buckle/get-go#1]
Hi Matt,

So i'm trying to conditionally enqueue javascript on certain pages via the hooks.php file.

In there, there is the wp wordpress init hook which I've added the following code.

```
add_action('init', function() {
    if (is_front_page()) {
        Theme::enqueueScript(
            'modal', 'jquery.modal.min'
        );
    } 
});
```

This unfortunately isn't working and the file isn't loading on the front page. When I remove the if statement it does load.

Thanks again!!

Tom

**Comment by Vyygir** [comment]
It does appear that you're correct. The `init` hook is run before WordPress has fulled loaded, so to conditionally enqueue scripts you'd be better off using the `wp_enqueue_scripts` hook, like so:

```php
add_action('wp_enqueue_scripts', function() {
    if (is_front_page()) {
        // Whichever script needs to be run on the homepage only
        Theme::enqueueScript('front-script-name', 'script-name');
    }

    Theme::enqueueScript('app', 'app');
});
```

Though it's worth noting that any other code executed in the `init` hook should be left there. I'll push a change in the future to address this, and handle asset queuing in a separate hook.

As you can see from the screenshots I've attached, I have two pages setup: the front page and a standard page. One shows an alert specific to the homepage, while the other shows an alert that will show on all other pages.

Feel free to get back to the ticket if you have any issues with this!

![image](https://user-images.githubusercontent.com/6696173/45978974-903d1a00-c045-11e8-9f4b-c4f038764c3f.png)
![image](https://user-images.githubusercontent.com/6696173/45979014-aba82500-c045-11e8-9e81-f5ea317868ce.png)
